### ISSUE TITLE
Autosaving a record fails on Rails 4.2

### ISSUE THREAD

**Issue by kakoni** [state-machines/state_machines-activerecord#6] opened 2015-01-30 21:50 UTC
Simple model looks like this (has status:string column)
```
class Event < ActiveRecord::Base

  state_machine :status, initial: :open do
    event :submit do
      transition [:open, :rejected] => :submitted
    end
    
    event :approve do
      transition submitted: :approved
    end

    event :reject do
      transition submitted: :rejected
    end
  end
end
```
Trying to change a state, expecting database update
```
Entry.new.submit
=> true
```
But nothing gets updated.

**Comment by seuros** [comment] 2015-01-30 22:22
Could you please tell the version of AR ?

**Comment by kakoni** [comment] 2015-01-30 22:50
* activerecord (4.2.0)

```
entry = Entry.new
entry.status
=> "open"
entry.submit
=> true
entry.status
=> "submitted"
```

**Comment by seuros** [comment] 2015-01-30 22:52
this is the expected behavior.

**Comment by kakoni** [comment] 2015-01-30 23:08
Oh my, of course it is. I was describing it wrong so take two;
```
entry = Entry.create
entry.submit
entry.status
=> "submitted"
entry.reload
entry.status
=> "open"
```
It should persist at submit, right?

**Comment by seuros** [comment] 2015-01-31 07:10
right :bug:

**Comment by adambrod** [comment] 2015-03-04 16:25
I've tested this in my app, and I can't reproduce this bug.  Was this bug fixed in the latest version, or is there an edge case I should be worried about before replacing state_machine with state_machines-activerecord in production?

**Comment by adambrod** [comment] 2015-03-04 16:29
I've tested this in my app (activerecord 4.2.0) and I can't reproduce this bug.  Is it possible this bug was fixed already?  Or is there an edgecase I should be worried about?  I'm planning to replace state_machine with state_machines-activerecord in production, but this bug makes me nervous that this gem isn't compatible with state_machine.

**Comment by seuros** [comment] 2015-03-04 18:12
This bug was fixed.

**Closed by seuros** 2015-03-04 18:12 UTC
Labels: bug
