### ISSUE TITLE
Wrong arity for initialize

### ISSUE THREAD

**Issue by kbennoune** [state-machines/state_machines-activerecord#56] opened 2017-06-06 18:25 UTC
Just came across an issue when upgrading an app from rails 4.2 to rails 5.0.

ActiveRecord::Base has an arity of 2 but the new method defined in define_state_initializer only has an arity of 1.  An error is thrown when super is called from a descendent that uses the options argument a 

ArgumentError "wrong number of arguments (given 2, expected 0..1)"

is thrown.

Thanks

**Comment by simi** [comment] 2017-08-25 23:37
Can you see this problem with latest version?

**Comment by rowanjt** [comment] 2017-10-11 17:21
I'm getting this issue with version 0.5.0.

**Comment by rafaelfranca** [comment] 2017-10-11 17:39
Can you please provide a sample application that reproduces the error?

**Comment by rowanjt** [comment] 2017-10-11 18:54
Can you tell me where the initialize method gets called that is defined by define_helper :instance ... located at state_machines-activerecord-0.5.0/lib/state_machines/integrations/active_record.rb @ line 452 ?
It seems to expect one arg for Rails 5 but it is being passed 2.

I can try to create a sample app to reproduce.

**Comment by rowanjt** [comment] 2017-10-11 19:05
Hmmm... Seems to be related to this other gem being used in our project...

protected_attributes_continued-1.3.0/lib/active_record/mass_assignment_security/persistence.rb:45:in `create'

which calls => object = new(attributes, options, &block)

when new just expects one argument

**Comment by rafaelfranca** [comment] 2017-10-11 19:27
Oh. That makes sense. So I'm closing this issue since it is not related with this project.

**Closed by rafaelfranca** 2017-10-11 19:27 UTC
